# Findphotospp.cmake - Find PHOTOS++ library
#
# This module defines:
#  PHOTOSPP_FOUND - system has PHOTOS++
#  PHOTOSPP_INCLUDE_DIRS - the PHOTOS++ include directories
#  PHOTOSPP_LIBRARIES - Link these to use PHOTOS++
#  PHOTOSPP_VERSION - PHOTOS++ version

find_path(PHOTOSPP_INCLUDE_DIR
  NAMES Photos/Photos.h
  HINTS ${PHOTOSPP_DIR} $ENV{PHOTOSPP_DIR} ${PHOTOSPP_ROOT_DIR} $ENV{PHOTOSPP_ROOT_DIR}
  PATH_SUFFIXES include
)

find_library(PHOTOSPP_LIBRARY
  NAMES Photospp
  HINTS ${PHOTOSPP_DIR} $ENV{PHOTOSPP_DIR} ${PHOTOSPP_ROOT_DIR} $ENV{PHOTOSPP_ROOT_DIR}
  PATH_SUFFIXES lib lib64
)

find_library(PHOTOSPP_HEPEVT_LIBRARY
  NAMES PhotosppHEPEVT
  HINTS ${PHOTOSPP_DIR} $ENV{PHOTOSPP_DIR} ${PHOTOSPP_ROOT_DIR} $ENV{PHOTOSPP_ROOT_DIR}
  PATH_SUFFIXES lib lib64
)

find_library(PHOTOSPP_HEPMC_LIBRARY
  NAMES PhotosppHepMC
  HINTS ${PHOTOSPP_DIR} $ENV{PHOTOSPP_DIR} ${PHOTOSPP_ROOT_DIR} $ENV{PHOTOSPP_ROOT_DIR}
  PATH_SUFFIXES lib lib64
)

find_library(PHOTOSPP_HEPMC3_LIBRARY
  NAMES PhotosppHepMC3
  HINTS ${PHOTOSPP_DIR} $ENV{PHOTOSPP_DIR} ${PHOTOSPP_ROOT_DIR} $ENV{PHOTOSPP_ROOT_DIR}
  PATH_SUFFIXES lib lib64
)

set(PHOTOSPP_LIBRARIES ${PHOTOSPP_LIBRARY})
if(PHOTOSPP_HEPEVT_LIBRARY)
  list(APPEND PHOTOSPP_LIBRARIES ${PHOTOSPP_HEPEVT_LIBRARY})
endif()
if(PHOTOSPP_HEPMC_LIBRARY)
  list(APPEND PHOTOSPP_LIBRARIES ${PHOTOSPP_HEPMC_LIBRARY})
endif()
if(PHOTOSPP_HEPMC3_LIBRARY)
  list(APPEND PHOTOSPP_LIBRARIES ${PHOTOSPP_HEPMC3_LIBRARY})
endif()

set(PHOTOSPP_INCLUDE_DIRS ${PHOTOSPP_INCLUDE_DIR})

# Extract version from Photos/Version.h if available
if(PHOTOSPP_INCLUDE_DIR AND EXISTS "${PHOTOSPP_INCLUDE_DIR}/Photos/Version.h")
  file(READ "${PHOTOSPP_INCLUDE_DIR}/Photos/Version.h" PHOTOSPP_VERSION_FILE)
  string(REGEX MATCH "PHOTOS_VERSION \"([0-9]+\\.[0-9]+)\"" PHOTOSPP_VERSION_MATCH ${PHOTOSPP_VERSION_FILE})
  if(PHOTOSPP_VERSION_MATCH)
    set(PHOTOSPP_VERSION ${CMAKE_MATCH_1})
  endif()
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(photospp
  REQUIRED_VARS PHOTOSPP_LIBRARY PHOTOSPP_INCLUDE_DIR
  VERSION_VAR PHOTOSPP_VERSION
)

mark_as_advanced(PHOTOSPP_INCLUDE_DIR PHOTOSPP_LIBRARY 
                 PHOTOSPP_HEPEVT_LIBRARY PHOTOSPP_HEPMC_LIBRARY PHOTOSPP_HEPMC3_LIBRARY)
