packages:
  gl:
    require:
      - glx
  libglx:
    require:
      - opengl
  egl:
    buildable: false
    externals:
      - spec: egl@1.5
        prefix: /usr
  opengl:
    buildable: false
    externals:
      - spec: opengl@4.6
        prefix: /usr
  openglu:
    buildable: false
    externals:
      - spec: openglu@1.4
        prefix: /usr
  mesa:
    require:
    - ~llvm
