from spack_repo.builtin.packages.py_onnxruntime.package import (
    PyOnnxruntime as BuiltinPyOnnxruntime,
)

from spack.package import *


class PyOnnxruntime(BuiltinPyOnnxruntime):
    __doc__ = BuiltinPyOnnxruntime.__doc__

    def cmake_args(self):
        args = super().cmake_args()
        if self.spec.satisfies("platform=darwin"):
            # onnxruntime's CMake always fetches its own pinned protoc (v21.12,
            # cmake/deps.txt) for any Apple host build, regardless of the
            # protobuf version Spack provides for linking (cmake/external/
            # onnxruntime_external_deps.cmake, CMAKE_HOST_APPLE branch). Code
            # generated by that old protoc is rejected by newer protobuf
            # headers: "This file was generated by a newer version of protoc
            # which is incompatible with your Protocol Buffer headers." Point
            # it at Spack's own protoc so codegen and linking use the same
            # protobuf version.
            args.append(
                self.define(
                    "ONNX_CUSTOM_PROTOC_EXECUTABLE", self.spec["protobuf"].prefix.bin.protoc
                )
            )
        return args
