name: Check for new versions

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  schedule:
    - cron: "0 13 * * 1" # Every Monday at 1PM UTC (9AM EST)

jobs:
  check-new-versions:
    runs-on: ubuntu-latest
    container: ghcr.io/spack/ubuntu-jammy:latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for new versions and create issue
      env:
        COMMENT_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        source /opt/spack/share/spack/setup-env.sh
        spack repo add --scope site ${GITHUB_WORKSPACE}
        .github/scripts/generate_new_version_issue.sh
        .github/scripts/post_new_version_issue_comment.sh
        
