name: Check for new versions

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  schedule:
    - cron: "0 13 * * 1,3,5" # Every Monday, Wednesday, Friday at 1PM UTC (9AM EST)

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/spack/ubuntu-jammy:latest
    defaults:
      run:
        shell: bash
        working-directory: .github/scripts/
    steps:
    - uses: actions/checkout@v2
    - name: Setup eic-spack repo
      run: |
        spack repo add --scope site ${GITHUB_WORKSPACE}
    - name: Check for new versions and create issue 
      env:
        COMMENT_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./generate_new_version_issue.sh
        ./post_new_version_issue_comment.sh
        
