name: Check for new versions

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1" # Every Monday at 1PM UTC (9AM EST)

jobs:
  check-new-versions:
    runs-on: ubuntu-latest
    container: ghcr.io/spack/ubuntu-jammy:latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for new versions and create issue
      env:
        COMMENT_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        source /opt/spack/share/spack/setup-env.sh
        spack repo add --scope site ${GITHUB_WORKSPACE}
        bash .github/scripts/checksum_new_versions.sh
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        branch-suffix: short-commit-hash
        title: New package versions found
        body: |
          New package versions found
        assignees: wdconinc
